version: "3"

volumes:
  krb5kdc-data:

services:
  kdc:
    container_name: krb5-server
    build: ./docker/kdc
    hostname: krb5-server
    ports:
      - "10088:88"
      - "10464:464"
      - "10749:749"
    environment:
      KRB5_REALM: REALM.SOKOIDE.COM
      KRB5_KDC: localhost
      KRB5_PASS: admin
    volumes:
      - ./tmp/krb5kdc-data:/var/lib/krb5kdc
    networks:
      - shared

  nginx:
    container_name: nginx-spnego
    build: ./docker/nginx-spnego
    hostname: nginx-spnego
    ports:
      - "20080:10080"
      - "20433:10433"
    volumes:
      - ./docker/nginx-spnego/data:/data
    networks:
      - shared

networks:
  shared:
    external:
      name: shared
  default:
    external:
      name: shared

